stages:
  face_embedding_pipeline:
    cmd: dvc repro pipelines/face_embedding/dvc.yaml

  fake_classification_pipeline:
    cmd: dvc repro pipelines/fake_classification/dvc.yaml

  emotion_classification_pipeline:
    cmd: dvc repro pipelines/emotion_classification/dvc.yaml
