stages:
  ingest:
    cmd: python mlops_xoxo/data_ingest.py
    deps:
      - mlops_xoxo/data_ingest.py
      - data/external/casioface/train.rec
      - data/external/casioface/train.idx
      - data/external/casioface/train.lst
    outs:
      - data/raw

  validate:
    cmd: python mlops_xoxo/data_validate.py
    deps:
      - mlops_xoxo/data_validate.py
      - data/raw
    outs:
      - docs

  split:
    cmd: python mlops_xoxo/data_split.py
    deps:
      - mlops_xoxo/data_split.py
      - data/raw
    outs:
      - data/processed

  train:
    cmd: python mlops_xoxo/train.py > mlflow_run_id.txt
    deps:
      - mlops_xoxo/train.py
      - data/processed/train
      - params.yaml
    params:
      - training
    outs:
      - models/face_embedding

  eval:
    cmd: python mlops_xoxo/eval.py
    deps:
      - mlops_xoxo/eval.py
      - models/face_embedding
      - data/processed/val
      - params.yaml
    outs:
      - reports
