# params.yaml
seed: 42
dataset:
  external_dir: data/external
  raw_dir: data/raw
  processed_dir: data/processed
  split: { train: 0.7, val: 0.15, test: 0.15 }
preprocessing:
  min_face_size: 40
  image_size: 160
training:
  batch_size: 64
  epochs: 20
  lr: 0.0001
  embedding_size: 512
  margin: 0.2
  weight_decay: 0.0001
  device: mps

mlflow:
  experiment_name: casioface_face_reid
  tracking_uri: https://dagshub.com/pawarit.jamjod/MLOps_XOXO.mlflow

storage:
  dvc_remote: https://dagshub.com/pawarit.jamjod/MLOps_XOXO.dvc
