dataset:
  external_dir: data/external/
  processed_dir: data/processed/
  raw_dir: data/raw/
  split:
    test: 0.15
    train: 0.7
    val: 0.15
mlflow:
  experiment_id: '5'
  experiment_name: fake_classification
  run_id: 83d7dafb82db4b08bed46cea90dda84b
  run_name: fake_classification_3_epochs
  tracking_uri: https://dagshub.com/pawarit.jamjod/MLOps_XOXO.mlflow
preprocessing:
  image_size: 224
  margin: 0.25
seed: 42
storage:
  dvc_remote: https://dagshub.com/pawarit.jamjod/MLOps_XOXO.dvc
training:
  backbone: mobilenet_v3_small
  batch_size: 64
  device: mps
  epochs: 100
  export_onnx: 1
  freeze_backbone: true
  lr: 0.001
  num_workers: 4
  weight_decay: 0.0001
