dataset:
  raw_dir: data/raw
  processed_dir: data/processed
  split:
    train: 0.7
    val: 0.15
    test: 0.15
mlflow:
  experiment_id: "4"
  experiment_name: emotion_classification
  run_id: a90bc793e451424fa50694dee3032877
  run_name: emotion_classification_200_epochs
  tracking_uri: https://dagshub.com/pawarit.jamjod/MLOps_XOXO.mlflow
preprocessing:
  image_size: 48
seed: 42
storage:
  dvc_remote: https://dagshub.com/pawarit.jamjod/MLOps_XOXO.dvc
training:
  epochs: 50
  batch_size: 32
  device: mps # Options: 'cuda' (NVIDIA GPU), 'gpu' (alias for cuda), 'mps' (Apple Silicon), 'cpu'
  lr: 0.001
  fraction: 1.0
  early_stopping_patience: 4
  save_onnx: false
